services:
  - type: web
    name: tinylink
    env: node
    region: singapore
    buildCommand: "npm install --legacy-peer-deps && npm install --workspace=backend --legacy-peer-deps && npm install --workspace=frontend --legacy-peer-deps && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: ""
      - key: BASE_URL
        value: ""