services:
  - type: web
    name: tinylink
    env: node
    region: singapore
    buildCommand: "pwd && ls -la && cd backend && pwd && npm install --production=false && npm run build && cd ../frontend && npm install --production=false && npm run build && cd .. && pwd"
    startCommand: "node backend/dist/server.js"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: ""
      - key: BASE_URL
        value: ""